import {
  BadRequestException,
  Injectable,
  Logger,
  ServiceUnavailableException,
  UnprocessableEntityException,
} from '@nestjs/common';
import {
  fetchTranscript,
  listLanguages,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptInvalidLangError,
  YoutubeTranscriptInvalidVideoIdError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptNotAvailableLanguageError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError,
} from 'youtube-transcript-plus';
import type {
  CaptionTrackInfo,
  FetchParams,
  TranscriptConfig,
  TranscriptResult,
} from 'youtube-transcript-plus';
import { decode } from 'he';

export type YoutubeTranscriptResult = TranscriptResult & { language: string };

const TRANSCRIPT_RETRIES = 2;
const TRANSCRIPT_RETRY_DELAY_MS = 500;

@Injectable()
export class YoutubeTranscriptAdapter {
  private readonly logger = new Logger(YoutubeTranscriptAdapter.name);
  private readonly transcriptConfigs: TranscriptConfig[] = [
    {
      retries: TRANSCRIPT_RETRIES,
      retryDelay: TRANSCRIPT_RETRY_DELAY_MS,
    },
    {
      retries: TRANSCRIPT_RETRIES,
      retryDelay: TRANSCRIPT_RETRY_DELAY_MS,
      playerFetch: this.fetchWebPlayer.bind(this),
    },
  ];

  async fetch(
    videoId: string,
    language: string,
  ): Promise<YoutubeTranscriptResult> {
    try {
      const candidateLanguages = await this.selectCaptionLanguages(
        videoId,
        language,
      );
      const result = await this.fetchFirstAvailable(
        videoId,
        candidateLanguages,
      );

      return {
        language: result.segments[0]?.lang ?? candidateLanguages[0] ?? language,
        ...result,
        videoDetails: {
          ...result.videoDetails,
          title: decode(result.videoDetails.title),
        },
        segments: result.segments.map((segment) => ({
          ...segment,
          text: decode(segment.text),
        })),
      };
    } catch (error) {
      if (error instanceof YoutubeTranscriptInvalidVideoIdError) {
        throw new BadRequestException('유효하지 않은 YouTube URL입니다.');
      }
      if (error instanceof YoutubeTranscriptInvalidLangError) {
        throw new BadRequestException('유효하지 않은 자막 언어 코드입니다.');
      }
      if (
        error instanceof YoutubeTranscriptDisabledError ||
        error instanceof YoutubeTranscriptNotAvailableError ||
        error instanceof YoutubeTranscriptNotAvailableLanguageError ||
        error instanceof YoutubeTranscriptVideoUnavailableError
      ) {
        throw new UnprocessableEntityException(
          '요청한 영상에서 해당 언어의 자막을 가져올 수 없습니다.',
        );
      }
      if (error instanceof YoutubeTranscriptTooManyRequestError) {
        throw new ServiceUnavailableException(
          'YouTube 요청이 일시적으로 제한되었습니다. 잠시 후 다시 시도해 주세요.',
        );
      }
      throw new ServiceUnavailableException(
        'YouTube 자막 서비스에 연결할 수 없습니다.',
      );
    }
  }

  private async selectCaptionLanguages(
    videoId: string,
    requestedLanguage: string,
  ): Promise<string[]> {
    const languages = await this.listLanguagesWithFallback(videoId);

    const requestedPrefix = requestedLanguage.split('-')[0];
    const candidates = [
      (track: CaptionTrackInfo) =>
        !track.isAutoGenerated && track.languageCode === requestedLanguage,
      (track: CaptionTrackInfo) =>
        track.isAutoGenerated && track.languageCode === requestedLanguage,
      (track: CaptionTrackInfo) =>
        !track.isAutoGenerated &&
        track.languageCode.toLowerCase().startsWith(`${requestedPrefix}-`),
      (track: CaptionTrackInfo) =>
        track.isAutoGenerated &&
        track.languageCode.toLowerCase().startsWith(`${requestedPrefix}-`),
      (track: CaptionTrackInfo) => track.isAutoGenerated,
      (track: CaptionTrackInfo) => !track.isAutoGenerated,
    ];

    const selected = candidates
      .map((match) => languages.find(match)?.languageCode)
      .filter((languageCode): languageCode is string => Boolean(languageCode));

    return [...new Set([requestedLanguage, ...selected])];
  }

  private async fetchFirstAvailable(
    videoId: string,
    candidateLanguages: string[],
  ): Promise<TranscriptResult> {
    let lastError: unknown;

    for (const language of candidateLanguages) {
      for (const config of this.transcriptConfigs) {
        try {
          return await this.fetchByLanguage(videoId, language, config);
        } catch (error) {
          lastError = error;
          this.logger.warn(
            `Failed to fetch YouTube transcript candidate lang=${language}: ${this.describeError(error)}`,
          );
        }
      }
    }

    for (const config of this.transcriptConfigs) {
      try {
        return await this.fetchByLanguage(videoId, undefined, config);
      } catch (error) {
        lastError = error;
        this.logger.warn(
          `Failed to fetch YouTube transcript without language: ${this.describeError(error)}`,
        );
      }
    }

    throw lastError;
  }

  private fetchByLanguage(
    videoId: string,
    language?: string,
    config: TranscriptConfig = this.transcriptConfigs[0],
  ): Promise<TranscriptResult> {
    return fetchTranscript(videoId, {
      ...config,
      ...(language ? { lang: language } : {}),
      videoDetails: true,
    });
  }

  private async listLanguagesWithFallback(videoId: string) {
    let lastError: unknown;

    for (const config of this.transcriptConfigs) {
      try {
        return await listLanguages(videoId, config);
      } catch (error) {
        lastError = error;
        this.logger.warn(
          `Failed to list YouTube caption languages: ${this.describeError(error)}`,
        );
      }
    }

    throw lastError;
  }

  private fetchWebPlayer(params: FetchParams): Promise<Response> {
    const body = this.toWebPlayerBody(params.body);

    return fetch(params.url, {
      method: params.method ?? 'POST',
      headers: {
        ...params.headers,
        ...(params.userAgent ? { 'User-Agent': params.userAgent } : {}),
      },
      body,
      signal: params.signal,
    });
  }

  private toWebPlayerBody(body: string | undefined) {
    if (!body) return body;

    const payload = JSON.parse(body) as {
      context?: {
        client?: Record<string, unknown>;
      };
    };

    payload.context ??= {};
    payload.context.client = {
      ...payload.context.client,
      clientName: 'WEB',
      clientVersion: '2.20260622.01.00',
      hl: 'en',
      gl: 'US',
    };

    return JSON.stringify(payload);
  }

  private describeError(error: unknown) {
    if (error instanceof Error) return `${error.name}: ${error.message}`;
    return String(error);
  }
}
