import { YoutubeTranscriptAdapter } from './youtube-transcript.adapter';
import { fetchTranscript, listLanguages } from 'youtube-transcript-plus';
import type { TranscriptResult } from 'youtube-transcript-plus';

jest.mock('youtube-transcript-plus', () => ({
  fetchTranscript: jest.fn(),
  listLanguages: jest.fn(),
  YoutubeTranscriptDisabledError: class YoutubeTranscriptDisabledError extends Error {},
  YoutubeTranscriptInvalidLangError: class YoutubeTranscriptInvalidLangError extends Error {},
  YoutubeTranscriptInvalidVideoIdError: class YoutubeTranscriptInvalidVideoIdError extends Error {},
  YoutubeTranscriptNotAvailableError: class YoutubeTranscriptNotAvailableError extends Error {},
  YoutubeTranscriptNotAvailableLanguageError: class YoutubeTranscriptNotAvailableLanguageError extends Error {},
  YoutubeTranscriptTooManyRequestError: class YoutubeTranscriptTooManyRequestError extends Error {},
  YoutubeTranscriptVideoUnavailableError: class YoutubeTranscriptVideoUnavailableError extends Error {},
}));

describe('YoutubeTranscriptAdapter', () => {
  const adapter = new YoutubeTranscriptAdapter();
  const mockedFetchTranscript =
    fetchTranscript as unknown as jest.MockedFunction<
      (
        videoId: string,
        config: { videoDetails: true },
      ) => Promise<TranscriptResult>
    >;
  const mockedListLanguages = jest.mocked(listLanguages);

  beforeEach(() => jest.clearAllMocks());

  it('요청 언어의 수동 자막이 없으면 자동 생성 자막을 사용한다', async () => {
    mockedListLanguages.mockResolvedValue([
      {
        languageCode: 'ko',
        languageName: 'Korean',
        isAutoGenerated: false,
      },
      {
        languageCode: 'en',
        languageName: 'English (auto-generated)',
        isAutoGenerated: true,
      },
    ]);
    mockedFetchTranscript.mockResolvedValue({
      videoDetails: {
        videoId: 'dQw4w9WgXcQ',
        title: 'Auto &amp; Caption',
        author: '',
        channelId: '',
        lengthSeconds: 10,
        viewCount: 0,
        description: '',
        keywords: [],
        thumbnails: [],
        isLiveContent: false,
      },
      segments: [
        {
          text: 'Hello &amp; welcome',
          duration: 2,
          offset: 0,
          lang: 'en',
        },
      ],
    });

    await expect(adapter.fetch('dQw4w9WgXcQ', 'en')).resolves.toMatchObject({
      language: 'en',
      videoDetails: { title: 'Auto & Caption' },
      segments: [{ text: 'Hello & welcome', lang: 'en' }],
    });
    expect(mockedFetchTranscript).toHaveBeenCalledWith(
      'dQw4w9WgXcQ',
      expect.objectContaining({ lang: 'en', videoDetails: true }),
    );
  });

  it('요청 언어가 없으면 같은 언어 계열의 자동 생성 자막을 우선 사용한다', async () => {
    mockedListLanguages.mockResolvedValue([
      {
        languageCode: 'en-US',
        languageName: 'English United States (auto-generated)',
        isAutoGenerated: true,
      },
    ]);
    mockedFetchTranscript.mockResolvedValue({
      videoDetails: {
        videoId: 'dQw4w9WgXcQ',
        title: 'Fallback',
        author: '',
        channelId: '',
        lengthSeconds: 10,
        viewCount: 0,
        description: '',
        keywords: [],
        thumbnails: [],
        isLiveContent: false,
      },
      segments: [
        {
          text: 'Fallback transcript',
          duration: 2,
          offset: 0,
          lang: 'en-US',
        },
      ],
    });

    await expect(adapter.fetch('dQw4w9WgXcQ', 'en')).resolves.toMatchObject({
      language: 'en-US',
      segments: [{ lang: 'en-US' }],
    });
    expect(mockedFetchTranscript).toHaveBeenCalledWith(
      'dQw4w9WgXcQ',
      expect.objectContaining({ lang: 'en-US', videoDetails: true }),
    );
  });
});
